# Generated by Django 3.0 on 2020-05-23 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runlocations',
            name='runID',
        ),
    ]
