# Generated by Django 3.0 on 2020-05-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0002_remove_runlocations_runid'),
    ]

    operations = [
        migrations.AddField(
            model_name='runlocations',
            name='blablabla',
            field=models.TextField(default='blbalabal'),
        ),
    ]
