# Generated by Django 3.0 on 2020-05-23 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0004_auto_20200523_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runlocations',
            name='blablabla',
        ),
        migrations.AddField(
            model_name='runlocations',
            name='runID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runID', to='run.Run'),
        ),
    ]
