# Generated by Django 3.0 on 2020-05-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0003_runlocations_blablabla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runlocations',
            name='blablabla',
            field=models.TextField(blank=True, null=True),
        ),
    ]
