# Generated by Django 3.0 on 2020-05-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0005_auto_20200523_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
