# Generated by Django 3.0 on 2019-12-26 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_menuitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
