# Generated by Django 3.0 on 2019-12-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.FloatField(default=0.5)),
                ('addTo', models.ManyToManyField(blank=True, related_name='manuItem', to='pizza.menuItem')),
            ],
        ),
    ]
