# Generated by Django 3.0 on 2019-12-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_auto_20191227_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topings',
            name='addTo',
        ),
        migrations.AddField(
            model_name='topings',
            name='menuItem',
            field=models.ManyToManyField(blank=True, related_name='items', to='pizza.menuItem'),
        ),
    ]
