# Generated by Django 3.0 on 2020-01-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_auto_20191227_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='toping',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topings',
            name='toping',
            field=models.IntegerField(default=0),
        ),
    ]
