# Generated by Django 3.0 on 2020-01-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_auto_20200103_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(default='none', max_length=64),
        ),
    ]
