# Generated by Django 3.0 on 2020-01-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='option1',
            field=models.CharField(default='none', max_length=64),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='option2',
            field=models.CharField(default='none', max_length=64),
        ),
    ]
