# Generated by Django 3.0 on 2020-01-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0009_auto_20200105_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='option2',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='option',
            field=models.IntegerField(default=0),
        ),
    ]
