# Generated by Django 3.0 on 2020-01-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0010_auto_20200105_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='option',
            field=models.FloatField(default=0),
        ),
    ]
