# Generated by Django 3.0 on 2020-01-05 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0011_auto_20200105_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='option',
            new_name='large',
        ),
    ]
