# Generated by Django 3.0 on 2020-01-16 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0013_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=64)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.menuItem')),
                ('topings', models.ManyToManyField(to='pizza.Topings')),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderItems',
            field=models.ManyToManyField(to='pizza.orderItem'),
        ),
    ]
